{{ include "gateway-api-inference-extension.validations.inferencepool.common" $ }}
apiVersion: inference.networking.k8s.io/v1
kind: InferencePool
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway-api-inference-extension.labels" . | nindent 4 }}
spec:
  targetPortNumber: {{ .Values.inferencePool.targetPortNumber }}
  selector:
    {{- if .Values.inferencePool.modelServers.matchLabels }}
    {{- range $key, $value := .Values.inferencePool.modelServers.matchLabels }}
    {{ $key }}: {{ quote $value }}
    {{- end }}
    {{- end }}
  extensionRef:
    name: {{ include "gateway-api-inference-extension.name" . }}
---
# IMPORTANT: Compatibility workaround: Mirror InferencePool with v1alpha2 API version
# Reference implementation EPP uses v1, but most Gateway API providers haven't transitioned to v1 yet
# This duplicate resource ensures compatibility across different provider versions
# TODO: Remove once all providers migrate to v1
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferencePool
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway-api-inference-extension.labels" . | nindent 4 }}
spec:
  targetPortNumber: {{ .Values.inferencePool.targetPortNumber }}
  selector:
    {{- if .Values.inferencePool.modelServers.matchLabels }}
    {{- range $key, $value := .Values.inferencePool.modelServers.matchLabels }}
    {{ $key }}: {{ quote $value }}
    {{- end }}
    {{- end }}
  extensionRef:
    name: {{ include "gateway-api-inference-extension.name" . }}
